export enum IndicatorType {
	overlay = 'overlay',
	indicator = 'indicator',
}

export type IndicatorOption = {
	name: string
	step: number
	min: number
	max?: number
}

export type IndicatorOutput = {
	name: string
	range?: [number, number]
}

export type IndicatorDescriptor = {
	key: string
	name: string
	type: IndicatorType
	options: IndicatorOption[]
	outputs: IndicatorOutput[]
}

export const makeDescriptor = (
	key: string,
	name: string,
	type: IndicatorType,
	options: (IndicatorOption | string)[],
	outputs: (IndicatorOutput | string)[],
): IndicatorDescriptor => ({
	key,
	name,
	type,
	options: options.map(
		(option): IndicatorOption =>
			typeof option === 'string' ? { name: option, min: 1, step: 1 } : option,
	),
	outputs: outputs.map(
		(output): IndicatorOutput =>
			typeof output === 'string' ? { name: output } : output,
	),
})

export const descriptors = {
	open: makeDescriptor(
		'open',
		'Open Price',
		IndicatorType.overlay,
		[],
		['open'],
	),
	high: makeDescriptor(
		'high',
		'High Price',
		IndicatorType.overlay,
		[],
		['high'],
	),
	low: makeDescriptor('low', 'Low Price', IndicatorType.overlay, [], ['low']),
	close: makeDescriptor(
		'close',
		'Close Price',
		IndicatorType.overlay,
		[],
		['close'],
	),
	volume: makeDescriptor(
		'volume',
		'Volume',
		IndicatorType.indicator,
		[],
		['volume'],
	),
	ad: makeDescriptor(
		'ad',
		'Accumulation/Distribution Line',
		IndicatorType.indicator,
		[],
		['ad'],
	),
	adosc: makeDescriptor(
		'adosc',
		'Accumulation/Distribution Oscillator',
		IndicatorType.indicator,
		['short period', 'long period'],
		['adosc'],
	),
	adx: makeDescriptor(
		'adx',
		'Average Directional Movement Index',
		IndicatorType.indicator,
		['period'],
		['dx'],
	),
	adx_slope: makeDescriptor(
		'adx_slope',
		'Average Directional Movement Index Slope',
		IndicatorType.indicator,
		['adx period', 'slope period'],
		['adx_slope'],
	),
	adxr: makeDescriptor(
		'adxr',
		'Average Directional Movement Rating',
		IndicatorType.indicator,
		['period'],
		['dx'],
	),
	ao: makeDescriptor(
		'ao',
		'Awesome Oscillator',
		IndicatorType.indicator,
		[],
		['ao'],
	),
	apo: makeDescriptor(
		'apo',
		'Absolute Price Oscillator',
		IndicatorType.indicator,
		['short period', 'long period'],
		['apo'],
	),
	aroon: makeDescriptor(
		'aroon',
		'Aroon',
		IndicatorType.indicator,
		['period'],
		[
			{ name: 'aroon_down', range: [0, 100] },
			{ name: 'aroon_up', range: [0, 100] },
		],
	),
	aroonosc: makeDescriptor(
		'aroonosc',
		'Aroon Oscillator',
		IndicatorType.indicator,
		['period'],
		[{ name: 'aroonosc', range: [-100, 100] }],
	),
	atr: makeDescriptor(
		'atr',
		'Average True Range',
		IndicatorType.indicator,
		['period'],
		['atr'],
	),
	avgprice: makeDescriptor(
		'avgprice',
		'Average Price',
		IndicatorType.overlay,
		[],
		['avgprice'],
	),
	bbands: makeDescriptor(
		'bbands',
		'Bollinger Bands',
		IndicatorType.overlay,
		['period', 'stddev'],
		['bbands_lower', 'bbands_middle', 'bbands_upper'],
	),
	bop: makeDescriptor(
		'bop',
		'Balance of Power',
		IndicatorType.indicator,
		[],
		['bop'],
	),
	cci: makeDescriptor(
		'cci',
		'Commodity Channel Index',
		IndicatorType.indicator,
		['period'],
		['cci'],
	),
	cmo: makeDescriptor(
		'cmo',
		'Chande Momentum Oscillator',
		IndicatorType.indicator,
		['period'],
		[{ name: 'cmo', range: [-100, 100] }],
	),
	cvi: makeDescriptor(
		'cvi',
		'Chaikins Volatility',
		IndicatorType.indicator,
		['period'],
		[{ name: 'cvi', range: [-100, 100] }],
	),
	dema: makeDescriptor(
		'dema',
		'Double Exponential Moving Average',
		IndicatorType.overlay,
		['period'],
		['dema'],
	),
	di: makeDescriptor(
		'di',
		'Directional Indicator',
		IndicatorType.indicator,
		['period'],
		[
			{ name: 'plus_di', range: [0, 100] },
			{ name: 'minus_di', range: [0, 100] },
		],
	),
	dm: makeDescriptor(
		'dm',
		'Directional Movement',
		IndicatorType.indicator,
		['period'],
		['plus_dm', 'minus_dm'],
	),
	dpo: makeDescriptor(
		'dpo',
		'Detrended Price Oscillator',
		IndicatorType.indicator,
		['period'],
		['dpo'],
	),
	dx: makeDescriptor(
		'dx',
		'Directional Movement Index',
		IndicatorType.indicator,
		['period'],
		[{ name: 'dx', range: [0, 100] }],
	),
	ema: makeDescriptor(
		'ema',
		'Exponential Moving Average',
		IndicatorType.overlay,
		['period'],
		['ema'],
	),
	emv: makeDescriptor(
		'emv',
		'Ease of Movement',
		IndicatorType.indicator,
		[],
		['emv'],
	),
	fisher: makeDescriptor(
		'fisher',
		'Fisher Transform',
		IndicatorType.indicator,
		['period'],
		['fisher', 'fisher_signal'],
	),
	fosc: makeDescriptor(
		'fosc',
		'Forecast Oscillator',
		IndicatorType.indicator,
		['period'],
		[{ name: 'fosc', range: [-100, 100] }],
	),
	ha_open: makeDescriptor(
		'ha_open',
		'Heikin Ashi Open',
		IndicatorType.overlay,
		[],
		['ha_open'],
	),
	ha_high: makeDescriptor(
		'ha_high',
		'Heikin Ashi High',
		IndicatorType.overlay,
		[],
		['ha_high'],
	),
	ha_low: makeDescriptor(
		'ha_low',
		'Heikin Ashi Low',
		IndicatorType.overlay,
		[],
		['ha_low'],
	),
	ha_close: makeDescriptor(
		'ha_close',
		'Heikin Ashi Close',
		IndicatorType.overlay,
		[],
		['ha_close'],
	),
	hma: makeDescriptor(
		'hma',
		'Hull Moving Average',
		IndicatorType.overlay,
		['period'],
		['hma'],
	),
	kama: makeDescriptor(
		'kama',
		'Kaufman Adaptive Moving Average',
		IndicatorType.overlay,
		['period'],
		['kama'],
	),
	kvo: makeDescriptor(
		'kvo',
		'Klinger Volume Oscillator',
		IndicatorType.indicator,
		['short period', 'long period'],
		['kvo'],
	),
	linreg: makeDescriptor(
		'linreg',
		'Linear Regression',
		IndicatorType.overlay,
		['period'],
		['linreg'],
	),
	linregintercept: makeDescriptor(
		'linregintercept',
		'Linear Regression Intercept',
		IndicatorType.indicator,
		['period'],
		['linregintercept'],
	),
	linregslope: makeDescriptor(
		'linregslope',
		'Linear Regression Slope',
		IndicatorType.indicator,
		['period'],
		['linregslope'],
	),
	macd: makeDescriptor(
		'macd',
		'Moving Average Convergence/Divergence',
		IndicatorType.indicator,
		['short period', 'long period', 'signal period'],
		['macd', 'macd_signal', 'macd_histogram'],
	),
	marketfi: makeDescriptor(
		'marketfi',
		'Market Facilitation Index',
		IndicatorType.indicator,
		[],
		['marketfi'],
	),
	mass: makeDescriptor(
		'mass',
		'Mass Index',
		IndicatorType.indicator,
		['period'],
		['mass'],
	),
	md: makeDescriptor(
		'md',
		'Mean Deviation Over Period',
		IndicatorType.indicator,
		['period'],
		['md'],
	),
	medprice: makeDescriptor(
		'medprice',
		'Median Price',
		IndicatorType.overlay,
		[],
		['medprice'],
	),
	mfi: makeDescriptor(
		'mfi',
		'Money Flow Index',
		IndicatorType.indicator,
		['period'],
		[{ name: 'mfi', range: [0, 100] }],
	),
	mom: makeDescriptor(
		'mom',
		'Momentum',
		IndicatorType.indicator,
		['period'],
		['mom'],
	),
	msw: makeDescriptor(
		'msw',
		'Mesa Sine Wave',
		IndicatorType.indicator,
		['period'],
		[
			{ name: 'msw_sine', range: [-1, 1] },
			{ name: 'msw_lead', range: [-1, 1] },
		],
	),
	natr: makeDescriptor(
		'natr',
		'Normalized Average True Range',
		IndicatorType.indicator,
		['period'],
		['natr'],
	),
	nvi: makeDescriptor(
		'nvi',
		'Negative Volume Index',
		IndicatorType.indicator,
		[],
		['nvi'],
	),
	obv: makeDescriptor(
		'obv',
		'On Balance Volume',
		IndicatorType.indicator,
		[],
		['obv'],
	),
	ppo: makeDescriptor(
		'ppo',
		'Percentage Price Oscillator',
		IndicatorType.indicator,
		['short period', 'long period'],
		['ppo'],
	),
	psar: makeDescriptor(
		'psar',
		'Parabolic SAR',
		IndicatorType.overlay,
		[
			{
				name: 'acceleration factor step',
				step: 0.1,
				min: 0,
				max: 1,
			},
			'acceleration factor maximum',
		],
		['psar'],
	),
	pvi: makeDescriptor(
		'pvi',
		'Positive Volume Index',
		IndicatorType.indicator,
		[],
		['pvi'],
	),
	qstick: makeDescriptor(
		'qstick',
		'Qstick',
		IndicatorType.indicator,
		['period'],
		['qstick'],
	),
	roc: makeDescriptor(
		'roc',
		'Rate of Change',
		IndicatorType.indicator,
		['period'],
		['roc'],
	),
	rocr: makeDescriptor(
		'rocr',
		'Rate of Change Ratio',
		IndicatorType.indicator,
		['period'],
		['rocr'],
	),
	rsi: makeDescriptor(
		'rsi',
		'Relative Strength Index',
		IndicatorType.indicator,
		['period'],
		[{ name: 'rsi', range: [0, 100] }],
	),
	sma: makeDescriptor(
		'sma',
		'Simple Moving Average',
		IndicatorType.overlay,
		['period'],
		['sma'],
	),
	stoch: makeDescriptor(
		'stoch',
		'Stochastic Oscillator',
		IndicatorType.indicator,
		['%k period', '%k slowing period', '%d period'],
		[
			{ name: 'stoch_k', range: [0, 100] },
			{ name: 'stoch_d', range: [0, 100] },
		],
	),
	stochrsi: makeDescriptor(
		'stochrsi',
		'Stochastic RSI',
		IndicatorType.indicator,
		['period'],
		[{ name: 'stochrsi', range: [0, 100] }],
	),
	tema: makeDescriptor(
		'tema',
		'Triple Exponential Moving Average',
		IndicatorType.overlay,
		['period'],
		['tema'],
	),
	tr: makeDescriptor('tr', 'True Range', IndicatorType.indicator, [], ['tr']),
	trima: makeDescriptor(
		'trima',
		'Triangular Moving Average',
		IndicatorType.overlay,
		['period'],
		['trima'],
	),
	trix: makeDescriptor(
		'trix',
		'Trix',
		IndicatorType.indicator,
		['period'],
		['trix'],
	),
	tsf: makeDescriptor(
		'tsf',
		'Time Series Forecast',
		IndicatorType.overlay,
		['period'],
		['tsf'],
	),
	typprice: makeDescriptor(
		'typprice',
		'Typical Price',
		IndicatorType.overlay,
		[],
		['typprice'],
	),
	ultosc: makeDescriptor(
		'ultosc',
		'Ultimate Oscillator',
		IndicatorType.indicator,
		['short period', 'medium period', 'long period'],
		[{ name: 'ultosc', range: [0, 100] }],
	),
	vhf: makeDescriptor(
		'vhf',
		'Vertical Horizontal Filter',
		IndicatorType.indicator,
		['period'],
		['vhf'],
	),
	vidya: makeDescriptor(
		'vidya',
		'Variable Index Dynamic Average',
		IndicatorType.overlay,
		[
			'short period',
			'long period',
			{
				name: 'alpha',
				max: 1,
				min: 0,
				step: 0.1,
			},
		],
		['vidya'],
	),
	volatility: makeDescriptor(
		'volatility',
		'Annualized Historical Volatility',
		IndicatorType.indicator,
		['period'],
		['volatility'],
	),
	vosc: makeDescriptor(
		'vosc',
		'Volume Oscillator',
		IndicatorType.indicator,
		['short period', 'long period'],
		['vosc'],
	),
	vwma: makeDescriptor(
		'vwma',
		'Volume Weighted Moving Average',
		IndicatorType.overlay,
		['period'],
		['vwma'],
	),
	wad: makeDescriptor(
		'wad',
		'Williams Accumulation/Distribution',
		IndicatorType.indicator,
		[],
		['wad'],
	),
	wcprice: makeDescriptor(
		'wcprice',
		'Weighted Close Price',
		IndicatorType.overlay,
		[],
		['wcprice'],
	),
	wilders: makeDescriptor(
		'wilders',
		'Wilders Smoothing',
		IndicatorType.overlay,
		['period'],
		['wilders'],
	),
	willr: makeDescriptor(
		'willr',
		'Williams %R',
		IndicatorType.indicator,
		['period'],
		[{ name: 'willr', range: [-100, 0] }],
	),
	wma: makeDescriptor(
		'wma',
		'Weighted Moving Average',
		IndicatorType.overlay,
		['period'],
		['wma'],
	),
	zlema: makeDescriptor(
		'zlema',
		'Zero-Lag Exponential Moving Average',
		IndicatorType.overlay,
		['period'],
		['zlema'],
	),
}
